# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spaceship.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fspaceship.proto\x12\tspaceship\">\n\x07Officer\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\t\"\xbc\x01\n\tSpaceship\x12\'\n\talignment\x18\x01 \x01(\x0e\x32\x14.spaceship.Alignment\x12\x0c\n\x04name\x18\x02 \x01(\t\x12 \n\x06\x63lass_\x18\x03 \x01(\x0e\x32\x10.spaceship.Class\x12\x0e\n\x06length\x18\x04 \x01(\x02\x12\x11\n\tcrew_size\x18\x05 \x01(\x05\x12\r\n\x05\x61rmed\x18\x06 \x01(\x08\x12$\n\x08officers\x18\x07 \x03(\x0b\x32\x12.spaceship.Officer\"\"\n\x0b\x43oordinates\x12\x13\n\x0b\x63oordinates\x18\x01 \x01(\t* \n\tAlignment\x12\x08\n\x04\x41LLY\x10\x00\x12\t\n\x05\x45NEMY\x10\x01*\\\n\x05\x43lass\x12\x0c\n\x08\x43ORVETTE\x10\x00\x12\x0b\n\x07\x46RIGATE\x10\x01\x12\x0b\n\x07\x43RUISER\x10\x02\x12\r\n\tDESTROYER\x10\x03\x12\x0b\n\x07\x43\x41RRIER\x10\x04\x12\x0f\n\x0b\x44READNOUGHT\x10\x05\x32V\n\x10ReportingService\x12\x42\n\x10ReportSpaceships\x12\x16.spaceship.Coordinates\x1a\x14.spaceship.Spaceship0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spaceship_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALIGNMENT']._serialized_start=321
  _globals['_ALIGNMENT']._serialized_end=353
  _globals['_CLASS']._serialized_start=355
  _globals['_CLASS']._serialized_end=447
  _globals['_OFFICER']._serialized_start=30
  _globals['_OFFICER']._serialized_end=92
  _globals['_SPACESHIP']._serialized_start=95
  _globals['_SPACESHIP']._serialized_end=283
  _globals['_COORDINATES']._serialized_start=285
  _globals['_COORDINATES']._serialized_end=319
  _globals['_REPORTINGSERVICE']._serialized_start=449
  _globals['_REPORTINGSERVICE']._serialized_end=535
# @@protoc_insertion_point(module_scope)
